name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: JJ/issue-greeting-action@releases/v0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        Greeting: 'Hey there! 👋\nWe noticed that this is your first time contributing in this repository. Make sure you read and understand the following:\n- Ideoxan''s [Code of Conduct](https://github.com/ideoxan/ideoxan/blob/master/CODE_OF_CONDUCT.md)\n- The [Contributing Guidelines](https://github.com/ideoxan/contributing)\n- Ideoxan''s [Privacy Policy](https://ideoxan.com/privacy)\n- Ideoxan''s [Terms of Service](https://ideoxan.com/tos).\n\nMake sure to follow the template for your issue/PR. Fill out as much details as you possibly can. Every little detail helps! If you have any questions reach out to us on our [Discord](https://discord.com/invite/jxqKy6r) or [Email Us](mailto:hello@ideoxan.com).\n\n**Thank you for your contribution**'
