name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  EXPRESS_SESSION_SECRET: abc123xyz890
  PWD_HASH: 8
  MAIL_DOMAIN: 0
  MAIL_KEY: 1234567890

jobs:
  test:
    name: Tests the Ideoxan server and website using Node v${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x, 15.x]
        mongodb-version: [4.4]

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Checkout submodules
      run: git submodule update --remote --init --recursive
      
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        
    - name: NPM Install, Build, and Test
      run: |
        npm install
        npm run build --if-present
        npm run test
